export const translations = {
    en: {
        sidebar: {
            settings: "Settings",
        },
        dashboard: {
            inventory: "Inventory",
            addItem: "Add Item",
            inventoryMenu: "Inventory Menu",
            myProducts: "My Products",
            bulk: "Bulk",
            stockIn: "Stock In",
        },
        inventoryTable: {
            searchPlaceholder: "Search items...",
            selectCategoryPlaceholder: "Select a category",
            allCategories: "All Categories",
            exportCsv: "Export CSV",
            name: "Name",
            size: "Size",
            price: "Price",
            currentStock: "Current Stock",
            actions: "Actions",
            updateStock: "Update Stock",
            viewHistory: "View History",
            noItems: "No items found.",
            editProduct: "Edit Product",
        },
        addItemDialog: {
            title: "Add New Item",
            description: "Enter the details of the new inventory item.",
            itemName: "Item Name",
            itemNamePlaceholder: "e.g., Organic Green Tea",
            category: "Category",
            categoryPlaceholder: "e.g., Beverages",
            price: "Price",
            pricePlaceholder: "e.g., 50000",
            initialStock: "Initial Stock",
            initialStockPlaceholder: "e.g., 100",
            addItem: "Add Item",
            itemAdded: "Item Added",
            hasBeenAdded: "has been added to the inventory.",
        },
        updateStockDialog: {
            stockUpdated: "Stock Updated",
            stockFor: "Stock for",
            hasBeenAdjusted: "has been adjusted.",
            title: "Update Stock for",
            description: "Enter a positive value to add stock or a negative value to remove it. Current stock:",
            stockAdjustment: "Stock Adjustment",
            stockAdjustmentPlaceholder: "e.g., -10 or 50",
            reason: "Reason for Adjustment",
            reasonPlaceholder: "e.g., Sale, New Shipment",
            updateStock: "Update Stock",
        },
        stockHistory: {
            title: "Stock History",
            description: "A log of all stock adjustments for this item.",
            date: "Date",
            reason: "Reason",
            change: "Change",
            newTotal: "New Total",
        },
        settings: {
            back: "Back",
            title: "Settings",
            appearance: "Appearance",
            appearanceDescription: "Customize the look and feel of the application.",
            theme: "Theme",
            selectThemePlaceholder: "Select theme",
            light: "Light",
            dark: "Dark",
            system: "System",
            language: "Language",
            languageDescription: "Choose your preferred language.",
            selectLanguagePlaceholder: "Select language",
        },
        bulkEditDialog: {
            title: "Edit Variants for",
            description: "Quickly edit all variants for this product below."
        },
        common: {
            cancel: "Cancel",
            saveChanges: "Save Changes",
        }
    },
    id: {
        sidebar: {
            settings: "Pengaturan",
        },
        dashboard: {
            inventory: "Inventaris",
            addItem: "Tambah Barang",
            inventoryMenu: "Menu Inventaris",
            myProducts: "Produk Saya",
            bulk: "Massal",
            stockIn: "Stok Masuk",
        },
        inventoryTable: {
            searchPlaceholder: "Cari barang...",
            selectCategoryPlaceholder: "Pilih kategori",
            allCategories: "Semua Kategori",
            exportCsv: "Ekspor CSV",
            name: "Nama",
            size: "Ukuran",
            price: "Harga",
            currentStock: "Stok Saat Ini",
            actions: "Aksi",
            updateStock: "Perbarui Stok",
            viewHistory: "Lihat Riwayat",
            noItems: "Tidak ada barang ditemukan.",
            editProduct: "Ubah Produk",
        },
        addItemDialog: {
            title: "Tambah Barang Baru",
            description: "Masukkan detail barang inventaris baru.",
            itemName: "Nama Barang",
            itemNamePlaceholder: "cth., Teh Hijau Organik",
            category: "Kategori",
            categoryPlaceholder: "cth., Minuman",
            price: "Harga",
            pricePlaceholder: "cth., 50000",
            initialStock: "Stok Awal",
            initialStockPlaceholder: "cth., 100",
            addItem: "Tambah Barang",
            itemAdded: "Barang Ditambahkan",
            hasBeenAdded: "telah ditambahkan ke inventaris.",
        },
        updateStockDialog: {
            stockUpdated: "Stok Diperbarui",
            stockFor: "Stok untuk",
            hasBeenAdjusted: "telah disesuaikan.",
            title: "Perbarui Stok untuk",
            description: "Masukkan nilai positif untuk menambah stok atau nilai negatif untuk menguranginya. Stok saat ini:",
            stockAdjustment: "Penyesuaian Stok",
            stockAdjustmentPlaceholder: "cth., -10 atau 50",
            reason: "Alasan Penyesuaian",
            reasonPlaceholder: "cth., Penjualan, Kiriman Baru",
            updateStock: "Perbarui Stok",
        },
        stockHistory: {
            title: "Riwayat Stok",
            description: "Log dari semua penyesuaian stok untuk barang ini.",
            date: "Tanggal",
            reason: "Alasan",
            change: "Perubahan",
            newTotal: "Total Baru",
        },
        settings: {
            back: "Kembali",
            title: "Pengaturan",
            appearance: "Tampilan",
            appearanceDescription: "Sesuaikan tampilan dan nuansa aplikasi.",
            theme: "Tema",
            selectThemePlaceholder: "Pilih tema",
            light: "Terang",
            dark: "Gelap",
            system: "Sistem",
            language: "Bahasa",
            languageDescription: "Pilih bahasa pilihan Anda.",
            selectLanguagePlaceholder: "Pilih bahasa",
        },
        bulkEditDialog: {
            title: "Ubah Varian untuk",
            description: "Ubah semua varian untuk produk ini dengan cepat di bawah."
        },
        common: {
            cancel: "Batal",
            saveChanges: "Simpan Perubahan",
        }
    }
}
