
export const translations = {
    en: {
        sidebar: {
            settings: "Settings",
        },
        dashboard: {
            inventory: "Inventory",
            addItem: "Add Item",
            inventoryMenu: "Inventory Menu",
            myProducts: "My Products",
            bulk: "Bulk Import",
            stockIn: "Stock In",
        },
        inventoryTable: {
            searchPlaceholder: "Search items...",
            selectCategoryPlaceholder: "Select a category",
            allCategories: "All Categories",
            exportCsv: "Export CSV",
            name: "Name",
            size: "Size",
            price: "Price",
            currentStock: "Current Stock",
            actions: "Actions",
            updateStock: "Update Stock",
            viewHistory: "View History",
            noItems: "No items found.",
            editProduct: "Edit Product",
        },
        addItemDialog: {
            title: "Add New Item",
            description: "Enter the details of the new inventory item.",
            itemName: "Item Name",
            itemNamePlaceholder: "e.g., Organic Green Tea",
            category: "Category",
            categoryPlaceholder: "e.g., Beverages",
            price: "Price",
            pricePlaceholder: "e.g., 50000",
            initialStock: "Initial Stock",
            initialStockPlaceholder: "e.g., 100",
            addItem: "Add Item",
            itemAdded: "Item Added",
            hasBeenAdded: "has been added to the inventory.",
        },
        updateStockDialog: {
            stockUpdated: "Stock Updated",
            stockFor: "Stock for",
            hasBeenAdjusted: "has been adjusted.",
            title: "Update Stock for",
            description: "Set the new total stock for this item. Current stock:",
            stockAdjustment: "Stock Adjustment",
            stockAdjustmentPlaceholder: "e.g., -10 or 50",
            newStockLevel: "New Stock Level",
            reason: "Reason for Adjustment",
            reasonPlaceholder: "e.g., Sale, New Shipment, Correction",
            updateStock: "Update Stock",
            stockMustBePositive: "Stock must be a non-negative number.",
            reasonRequired: "Reason must be at least 2 characters.",
        },
        stockHistory: {
            title: "Stock History",
            description: "A log of all stock adjustments for this item.",
            date: "Date",
            reason: "Reason",
            change: "Change",
            newTotal: "New Total",
            searchPlaceholder: "Search by product name or reason...",
            dateRange: "Date Range",
        },
        stockInForm: {
            title: "Record Stock In",
            description: "Add new stock received from suppliers or other sources.",
            selectProducts: "Select Products",
            noProducts: "No products selected.",
            quantity: "Quantity",
            reason: "Reason / Note",
            submit: "Submit Stock In",
            successTitle: "Stock In Successful",
            successDescription: "{count} item(s) have been updated.",
            bulkAdd: "Bulk Add",
        },
        productSelectionDialog: {
            title: "Select Products",
            description: "Choose products to add to the stock in list. You can search, filter, and select multiple items.",
            searchPlaceholder: "Search by product or SKU...",
            categoryPlaceholder: "Filter by category...",
            addItems: "Add {count} Items",
            itemsSelected: "{count} item(s) selected.",
            previous: "Previous",
            next: "Next",
            page: "Page",
            of: "of",
        },
        settings: {
            back: "Back",
            title: "Settings",
            appearance: "Appearance",
            appearanceDescription: "Customize the look and feel of the application.",
            theme: "Theme",
            selectThemePlaceholder: "Select theme",
            light: "Light",
            dark: "Dark",
            system: "System",
            language: "Language",
            languageDescription: "Choose your preferred language.",
            selectLanguagePlaceholder: "Select language",
        },
        bulkEditDialog: {
            title: "Edit Variants for",
            description: "Quickly edit all variants for this product below."
        },
        bulkStockInDialog: {
            title: "Bulk Stock In",
            description: "Quickly set quantity and reason for all selected items. This will overwrite existing values.",
            variantName: "Variant Name",
            applyToAll: "Apply to All",
            applyReasonPlaceholder: "Set a reason for all variants...",
            hasVariants: "This product has multiple variants (e.g., sizes, colors)",
            variants: "Variants",
            variantsDescription: "Add variants for your product. Each variant can have its own SKU, price, and stock level.",
            addVariant: "Add Variant"
        },
        common: {
            cancel: "Cancel",
            saveChanges: "Save Changes",
            apply: "Apply",
        }
    },
    id: {
        sidebar: {
            settings: "Pengaturan",
        },
        dashboard: {
            inventory: "Inventaris",
            addItem: "Tambah Barang",
            inventoryMenu: "Menu Inventaris",
            myProducts: "Produk Saya",
            bulk: "Impor Massal",
            stockIn: "Stok Masuk",
        },
        inventoryTable: {
            searchPlaceholder: "Cari barang...",
            selectCategoryPlaceholder: "Pilih kategori",
            allCategories: "Semua Kategori",
            exportCsv: "Ekspor CSV",
            name: "Nama",
            size: "Ukuran",
            price: "Harga",
            currentStock: "Stok Saat Ini",
            actions: "Aksi",
            updateStock: "Perbarui Stok",
            viewHistory: "Lihat Riwayat",
            noItems: "Tidak ada barang ditemukan.",
            editProduct: "Ubah Produk",
        },
        addItemDialog: {
            title: "Tambah Barang Baru",
            description: "Masukkan detail barang inventaris baru.",
            itemName: "Nama Barang",
            itemNamePlaceholder: "cth., Teh Hijau Organik",
            category: "Kategori",
            categoryPlaceholder: "cth., Minuman",
            price: "Harga",
            pricePlaceholder: "cth., 50000",
            initialStock: "Stok Awal",
            initialStockPlaceholder: "cth., 100",
            addItem: "Tambah Barang",
            itemAdded: "Barang Ditambahkan",
            hasBeenAdded: "telah ditambahkan ke inventaris.",
        },
        updateStockDialog: {
            stockUpdated: "Stok Diperbarui",
            stockFor: "Stok untuk",
            hasBeenAdjusted: "telah disesuaikan.",
            title: "Perbarui Stok untuk",
            description: "Atur jumlah stok total baru untuk barang ini. Stok saat ini:",
            stockAdjustment: "Penyesuaian Stok",
            stockAdjustmentPlaceholder: "cth., -10 atau 50",
            newStockLevel: "Jumlah Stok Baru",
            reason: "Alasan Penyesuaian",
            reasonPlaceholder: "cth., Penjualan, Kiriman Baru, Koreksi",
            updateStock: "Perbarui Stok",
            stockMustBePositive: "Stok harus berupa angka non-negatif.",
            reasonRequired: "Alasan harus diisi minimal 2 karakter.",
        },
        stockHistory: {
            title: "Riwayat Stok",
            description: "Log dari semua penyesuaian stok untuk barang ini.",
            date: "Tanggal",
            reason: "Alasan",
            change: "Perubahan",
            newTotal: "Total Baru",
            searchPlaceholder: "Cari berdasarkan nama produk atau alasan...",
            dateRange: "Rentang Tanggal",
        },
        stockInForm: {
            title: "Catat Stok Masuk",
            description: "Tambahkan stok baru yang diterima dari pemasok atau sumber lain.",
            selectProducts: "Pilih Produk",
            noProducts: "Belum ada produk dipilih.",
            quantity: "Jumlah",
            reason: "Alasan / Catatan",
            submit: "Kirim Stok Masuk",
            successTitle: "Stok Masuk Berhasil",
            successDescription: "{count} barang telah diperbarui.",
            bulkAdd: "Tambah Massal",
        },
        productSelectionDialog: {
            title: "Pilih Produk",
            description: "Pilih produk untuk ditambahkan ke daftar stok masuk. Anda dapat mencari, memfilter, dan memilih beberapa item.",
            searchPlaceholder: "Cari berdasarkan produk atau SKU...",
            categoryPlaceholder: "Filter berdasarkan kategori...",
            addItems: "Tambah {count} Barang",
            itemsSelected: "{count} barang dipilih.",
            previous: "Sebelumnya",
            next: "Berikutnya",
            page: "Halaman",
            of: "dari",
        },
        settings: {
            back: "Kembali",
            title: "Pengaturan",
            appearance: "Tampilan",
            appearanceDescription: "Sesuaikan tampilan dan nuansa aplikasi.",
            theme: "Tema",
            selectThemePlaceholder: "Pilih tema",
            light: "Terang",
            dark: "Gelap",
            system: "Sistem",
            language: "Bahasa",
            languageDescription: "Pilih bahasa pilihan Anda.",
            selectLanguagePlaceholder: "Pilih bahasa",
        },
        bulkEditDialog: {
            title: "Ubah Varian untuk",
            description: "Ubah semua varian untuk produk ini dengan cepat di bawah."
        },
        bulkStockInDialog: {
            title: "Stok Masuk Massal",
            description: "Atur jumlah dan alasan untuk semua barang terpilih dengan cepat. Ini akan menimpa nilai yang sudah ada.",
            variantName: "Nama Varian",
            applyToAll: "Terapkan ke Semua",
            applyReasonPlaceholder: "Atur alasan untuk semua varian...",
            hasVariants: "Produk ini memiliki banyak varian (misalnya ukuran, warna)",
            variants: "Varian",
            variantsDescription: "Tambahkan varian untuk produk Anda. Setiap varian dapat memiliki SKU, harga, dan tingkat stok sendiri.",
            addVariant: "Tambah Varian"
        },
        common: {
            cancel: "Batal",
            saveChanges: "Simpan Perubahan",
            apply: "Terapkan",
        }
    }
}
