

export const translations = {
    en: {
        sidebar: {
            settings: "Settings",
        },
        dashboard: {
            inventory: "My Products",
            addItem: "Add Item",
            addAccessory: "Add Accessory",
            inventoryMenu: "Inventory",
            myProducts: "My Products",
            accessories: "Accessories",
            bulk: "Bulk Add",
            stockIn: "Stock In",
        },
        sales: {
            title: "Sales",
            shopee: "Shopee",
            tiktok: "Tiktok",
            lazada: "Lazada",
            pos: "POS",
            reseller: "Reseller",
        },
        shipping: {
            title: "Shipping",
            receipt: "Receipts",
            return: "Returns",
            report: "Receipt Report",
            receiptPage: {
                title: "Shipping Receipts",
                searchPlaceholder: "Search AWB...",
                selectDate: "Select date",
                processSelected: "Process Shipment",
                processing: "Processing...",
                selectAll: "Select all",
                select: "Select",
                table: {
                    awb: "AWB Number",
                    date: "Date",
                    channel: "Channel",
                    status: "Status",
                    actions: "Actions",
                },
                actions: {
                    processShipment: "Process Shipment",
                    cancel: "Cancel",
                    markAsDone: "Mark as Done",
                    markAsReturn: "Mark as Return",
                },
                loading: "Loading data...",
                noReceiptsTitle: "No Receipts Found",
                noReceiptsDesc: "Receipts you scan or input will appear here.",
                deleteConfirmTitle: "Delete This Receipt?",
                deleteConfirmDesc: "Are you sure you want to delete receipt {awb}? This action cannot be undone.",
                deleteConfirmAction: "Yes, Delete",
                fetchError: "Failed to load receipt data.",
                deleteSuccess: "Receipt Deleted",
                deleteSuccessDesc: "Receipt {awb} has been successfully deleted.",
                deleteError: "Failed to delete receipt.",
                statusUpdateSuccess: "Status Updated",
                statusUpdateSuccessDesc: "Receipt status has been updated to \"{status}\".",
                statusUpdateError: "Failed to Update Status",
                statusUpdateErrorDesc: "An error occurred while changing the status.",
                bulkProcessSuccess: "Receipts Processed",
                bulkProcessSuccessDesc: "{count} receipts have been successfully updated to \"Shipped\".",
                bulkProcessError: "Failed to Process",
                bulkProcessErrorDesc: "An error occurred while updating receipt statuses.",
            },
            returnPage: {
                title: "Manage Returns & Cancellations",
                table: {
                    awb: "AWB Number",
                    date: "Date",
                    channel: "Channel",
                    status: "Status",
                    actions: "Actions",
                },
                actions: {
                    process: "Process",
                    itemArrived: "Item Arrived",
                    itemInTransit: "Item In Transit",
                    itemNotArrived: "Item Not Arrived",
                    delete: "Delete",
                },
                loading: "Loading data...",
                noReturnsTitle: "No Return Data",
                noReturnsDesc: "All return/cancelled receipts will appear here.",
                fetchError: "Failed to load return data.",
                statusUpdateSuccess: "Status Updated",
                statusUpdateSuccessDesc: "Receipt status has been updated to \"{status}\".",
                statusUpdateError: "Failed to Update Status",
                processReturn: "Process Return",
                selectReturnedItem: "Select the returned product to add it back to stock.",
                stockReturnedSuccess: "Stock Returned",
                stockReturnedSuccessDesc: "1 unit of {name} has been added back to stock.",
                stockReturnedError: "Failed to return stock.",
                deleteConfirmTitle: "Delete This Return?",
                deleteConfirmDesc: "Are you sure you want to delete the return record for {awb}? This action cannot be undone.",
                deleteConfirmAction: "Yes, Delete",
                deleteSuccess: "Return Deleted",
                deleteSuccessDesc: "Return record for {awb} has been successfully deleted.",
                deleteError: "Failed to delete return record.",
            },
            reportPage: {
                title: "Receipt Report",
                selectMonth: "Select Month",
                selectYear: "Select Year",
                table: {
                    date: "Date",
                    pending: "Pending",
                    shipped: "Shipped",
                    cancelled: "Cancelled",
                    returned: "Returned",
                    total: "Total Receipts",
                },
                fetchError: "Failed to load report data.",
                noDataTitle: "No Data",
                noDataDesc: "No receipt data found for the selected month.",
            }
        },
        finance: {
            title: "Finance",
            generalJournal: "General Journal",
            generalLedger: "General Ledger",
            financialStatements: "Financial Statements",
            assetReport: "Asset Report",
            profitLossReport: "Profit & Loss Report",
            priceSettings: "Price Settings",
            balanceSheet: "Balance Sheet",
            priceSettingsPage: {
                description: "Select products to set their cost price, default selling price, and channel-specific prices.",
                selectProduct: "Select Product",
                searchPlaceholder: "Search products in the table...",
                product: "Product",
                costPrice: "Cost Price",
                defaultPrice: "Default Price",
                onlinePrice: "Online Price",
                sellingPrices: "Selling Prices",
                noProducts: "No products selected.",
                selectProductsCta: "Select products to start setting prices.",
                saveAll: "Save All Changes",
                successToast: "Prices Updated",
                successToastDesc: "All price changes have been saved successfully.",
                errorToast: "Update Failed",
                channelPriceDetails: "Channel Price Details",
            },
            assetReportPage: {
                totalAssetValue: "Total Asset Value",
                fastLabel: "Fast-Moving",
                slowLabel: "Slow-Moving",
                nonMovingLabel: "Non-Moving",
                chartTitle: "Asset Turnover Chart",
                chartXAxisLabel: "Asset Classification",
                topFastMoving: "Top 10 Fast-Moving Products",
                topSlowMoving: "Top 10 Slow-Moving Products",
                topNonMoving: "Top 10 Non-Moving Products",
                productColumn: "Product",
                unitsSoldColumn: "Units Sold",
                stockValueColumn: "Stock Value",
                noProductsInCategory: "No products in this category."
            }
        },
        inventoryTable: {
            searchPlaceholder: "Search items...",
            selectCategoryPlaceholder: "Select a category",
            allCategories: "All Categories",
            exportCsv: "Export CSV",
            name: "Name",
            size: "Size",
            price: "Price",
            currentStock: "Current Stock",
            actions: "Actions",
            updateStock: "Update Stock",
            viewHistory: "View History",
            noItems: "No items found.",
            editProduct: "Edit Product",
            allStock: "All",
            lowStock: "Low Stock",
            emptyStock: "Empty Stock",
        },
        archived: {
            title: "Archived Products",
            searchPlaceholder: "Search archived products...",
            archiveButton: "Archive",
            unarchiveButton: "Reactivate",
            deleteButton: "Delete",
            table: {
                product: "Product",
                category: "Category",
                actions: "Actions",
            },
            loading: "Loading archived products...",
            empty: "No Archived Products",
            archiveSuccessTitle: "Product Archived",
            archiveSuccessDesc: "The product has been successfully archived.",
            archiveErrorTitle: "Failed to Archive",
            archiveErrorDesc: "An error occurred while archiving the product.",
            unarchiveSuccessTitle: "Product Reactivated",
            unarchiveSuccessDesc: "The product has been successfully returned to the active list.",
            unarchiveErrorTitle: "Failed to Reactivate Product",
            unarchiveErrorDesc: "An error occurred while reactivating the product.",
            archiveDialogTitle: "Archive This Product?",
            archiveDialogDesc: "Archived products will be hidden from the main list and cannot be sold. You can reactivate them later.",
            archiveDialogConfirm: "Yes, Archive",
            deleteDialogTitle: "Delete Product Permanently?",
            deleteDialogDesc: "This will permanently delete '{name}' and all its data. This action cannot be undone.",
            deleteDialogConfirm: "Yes, Delete Permanently",
            deleteSuccessTitle: "Product Deleted",
            deleteSuccessDesc: "{name} has been permanently deleted.",
            deleteErrorTitle: "Deletion Failed",
            deleteErrorDesc: "An error occurred while deleting the product."
        },
        addItemDialog: {
            title: "Add New Item",
            description: "Enter the details of the new inventory item.",
            itemName: "Item Name",
            itemNamePlaceholder: "e.g., Organic Green Tea",
            category: "Category",
            categoryPlaceholder: "Pilih Kategori",
            price: "Price",
            pricePlaceholder: "e.g., 50000",
            initialStock: "Initial Stock",
            initialStockPlaceholder: "e.g., 100",
            addItem: "Add Item",
            itemAdded: "Item Added",
            hasBeenAdded: "has been added to the inventory.",
        },
        updateStockDialog: {
            stockUpdated: "Stock Updated",
            stockFor: "Stock for",
            hasBeenAdjusted: "has been adjusted.",
            title: "Update Stock",
            description: "Current stock:",
            stockAdjustment: "Stock Change",
            stockAdjustmentPlaceholder: "e.g., +10 for stock in, -5 for stock out",
            newStockLevel: "New Stock Level",
            reason: "Reason for Adjustment",
            reasonPlaceholder: "e.g., Sale, New Shipment, Correction",
            updateStock: "Update Stock",
            stockMustBePositive: "Stock must be a non-negative number.",
            reasonRequired: "Reason must be at least 2 characters.",
        },
        stockHistory: {
            title: "Stock History",
            description: "A log of all stock adjustments for this item.",
            date: "Date",
            reason: "Reason",
            change: "Change",
            newTotal: "New Total",
            searchPlaceholder: "Search by product name or reason...",
            dateRange: "Date Range",
        },
        stockInForm: {
            title: "Record Stock In",
            description: "Add new stock received from suppliers or other sources.",
            selectProducts: "Select Products",
            noProducts: "No products selected.",
            quantity: "Quantity",
            reason: "Reason / Note",
            submit: "Submit Stock In",
            successTitle: "Stock In Successful",
            successDescription: "{count} item(s) have been updated.",
            bulkAdd: "Bulk Add",
        },
        productSelectionDialog: {
            title: "Select Products",
            description: "Choose products to add to the list. You can search, filter, and select multiple items.",
            searchPlaceholder: "Search by product or SKU...",
            categoryPlaceholder: "Filter by category...",
            addItems: "Add {count} Items",
            itemsPerPage: "Showing {start}-{end} of {total} items.",
            previous: "Previous",
            next: "Next",
            page: "page",
            of: "of",
        },
        variantSelectionDialog: {
            title: "Select Variant",
            description: "This product has multiple variants. Please select one to continue the sale."
        },
        pos: {
            title: "Point of Sale",
            searchPlaceholder: "Scan SKU or search product name...",
            noResults: "No products found.",
            noStock: "Out of stock",
            orderSummary: "Order Summary",
            item: "Item",
            qty: "Qty",
            price: "Price",
            subtotal: "Subtotal",
            emptyCart: "Cart is empty",
            paymentDetails: "Payment Details",
            discount: "Discount (Rp)",
            tax: "Tax (%)",
            cashReceived: "Cash Received",
            total: "Total",
            change: "Change",
            completeSale: "Complete Sale",
            saleCompleted: "Sale Completed",
            transactionId: "Transaction ID:",
            printReceipt: "Print Receipt",
            newSale: "New Sale",
            history: "Transaction History",
            cancel: "Cancel Sale",
            transactionCancelled: "Transaction Cancelled",
            paymentMethod: "Payment Method",
            cash: "Cash"
        },
        reseller: {
            selectTitle: "Select Reseller",
            selectDescription: "Select a reseller to start a transaction.",
            selectOrCreate: "Select or Add Reseller",
            historyTitle: "Reseller Transaction History",
            transactionsOnDate: "Transactions on {date}",
            transactionsDescription: "Showing all transactions from the Reseller channel.",
            noTransactions: "No Transactions",
            noTransactionsDesc: "No transactions recorded on the selected date.",
            history: {
                time: "Time",
                reseller: "Reseller",
                transactionDetails: "Transaction Details",
                paymentMethod: "Payment Method",
                total: "Total",
                actions: "Actions"
            },
            dialog: {
                title: "Select Reseller",
                description: "Select a reseller from the list below, or add a new one.",
                addNew: "Add New Reseller",
                searchPlaceholder: "Search reseller...",
                table: {
                    name: "Name",
                    phone: "Phone Number",
                    address: "Address",
                    actions: "Actions",
                },
                form: {
                    addTitle: "Add New Reseller",
                    addDescription: "Enter the new reseller's details below.",
                    editTitle: "Edit Reseller",
                    editDescription: "Change the reseller's details below.",
                    nameLabel: "Reseller Name",
                    namePlaceholder: "Name...",
                    phoneLabel: "Phone No.",
                    phonePlaceholder: "0812...",
                    addressLabel: "Address",
                    addressPlaceholder: "Short address...",
                    save: "Save Reseller"
                },
                deleteDialog: {
                    title: "Are you sure you want to delete this reseller?",
                    description: "This action cannot be undone. This will permanently delete the reseller '{name}'.",
                    confirm: "Yes, Delete"
                },
                addedToast: "Reseller Added",
                addedToastDesc: "Reseller '{name}' has been successfully added.",
                addErrorToast: "Failed to Add",
                updatedToast: "Reseller Updated",
                updatedToastDesc: "Data for '{name}' has been updated.",
                updateErrorToast: "Failed to Update",
                deletedToast: "Reseller Deleted",
                deletedToastDesc: "Reseller '{name}' has been deleted.",
                deleteErrorToast: "Failed to Delete",
                notFound: "Reseller not found.",
                none: "No resellers yet. Add one above."
            }
        },
        receipt: {
            shopName: "WaveApp Store",
            thankYou: "Thank you for your purchase!",
            date: "Date",
            receiptNo: "Receipt No",
            cashier: "Cashier",
            paymentMethod: "Payment Method",
            item: "Item",
            qty: "Qty",
            price: "Price",
            total: "Total",
            subtotal: "Subtotal",
            discount: "Discount",
            grandTotal: "Grand Total",
            cash: "Cash",
            change: "Change",
        },
        settings: {
            back: "Back",
            title: "Settings",
            appearance: "Appearance",
            appearanceDescription: "Customize the look and feel of the application.",
            theme: "Theme",
            selectThemePlaceholder: "Select theme",
            light: "Light",
            dark: "Dark",
            system: "System",
            language: "Language",
            languageDescription: "Choose your preferred language.",
            selectLanguagePlaceholder: "Select language",
        },
        bulkEditDialog: {
            title: "Adjust Stock",
            parentSkuLabel: "Parent SKU",
            bulkStockPlaceholder: "Set All Stock",
            applyToAll: "Apply All",
            variationColumn: "Variation",
            totalStockColumn: "Total Stock",
            reasonLabel: "Adjustment Reason",
            reasonPlaceholder: "e.g., Stock Opname, Correction...",
            defaultReason: "Mass Stock Adjustment",
            successToastTitle: "Variants Updated",
            successToastDesc: "Stock for {name} variants has been updated.",
            invalidValueToastTitle: "Invalid Value",
            invalidValueToastDesc: "Please enter a valid stock amount (non-negative number)."
        },
        bulkStockInDialog: {
            title: "Bulk Stock In",
            description: "Quickly set quantity and reason for all selected items. This will overwrite existing values.",
            variantName: "Variant Name",
            applyToAll: "Apply to All",
            applyReasonPlaceholder: "Set a reason for all variants...",
            hasVariants: "This product has multiple variants (e.g., sizes, colors)",
            variants: "Variants",
            variantsDescription: "Add variants for your product. Each variant can have its own SKU, price, and stock level.",
            addVariant: "Add Variant"
        },
        common: {
            cancel: "Cancel",
            saveChanges: "Save Changes",
            apply: "Apply",
            saving: "Saving...",
            update: "Update",
        }
    },
    id: {
        sidebar: {
            settings: "Pengaturan",
        },
        dashboard: {
            inventory: "Produk Saya",
            addItem: "Tambah Barang",
            addAccessory: "Tambah Aksesoris",
            inventoryMenu: "Inventaris",
            myProducts: "Produk Saya",
            accessories: "Aksesoris",
            bulk: "Tambah Masal",
            stockIn: "Stok Masuk",
        },
        sales: {
            title: "Penjualan",
            shopee: "Shopee",
            tiktok: "Tiktok",
            lazada: "Lazada",
            pos: "POS",
            reseller: "Reseller",
        },
        shipping: {
            title: "Pengiriman",
            receipt: "Resi",
            return: "Return",
            report: "Laporan Resi",
            receiptPage: {
                title: "Resi Pengiriman",
                searchPlaceholder: "Cari No. Resi...",
                selectDate: "Pilih tanggal",
                processSelected: "Proses Kirim",
                processing: "Memproses...",
                selectAll: "Pilih semua",
                select: "Pilih",
                table: {
                    awb: "No. Resi (AWB)",
                    date: "Tanggal",
                    channel: "Channel",
                    status: "Status",
                    actions: "Aksi",
                },
                actions: {
                    processShipment: "Proses Kirim",
                    cancel: "Batalkan",
                    markAsDone: "Tandai Selesai",
                    markAsReturn: "Tandai Return",
                },
                loading: "Memuat data...",
                noReceiptsTitle: "Tidak Ada Resi",
                noReceiptsDesc: "Resi yang Anda pindai atau input akan muncul di sini.",
                deleteConfirmTitle: "Hapus Resi Ini?",
                deleteConfirmDesc: "Anda yakin ingin menghapus resi {awb}? Tindakan ini tidak dapat diurungkan.",
                deleteConfirmAction: "Ya, Hapus",
                fetchError: "Gagal memuat data resi.",
                deleteSuccess: "Resi dihapus",
                deleteSuccessDesc: "Resi {awb} telah berhasil dihapus.",
                deleteError: "Gagal menghapus resi.",
                statusUpdateSuccess: "Status Diperbarui",
                statusUpdateSuccessDesc: "Status resi telah diubah menjadi \"{status}\".",
                statusUpdateError: "Gagal Memperbarui Status",
                statusUpdateErrorDesc: "Terjadi kesalahan saat mengubah status.",
                bulkProcessSuccess: "Resi Diproses",
                bulkProcessSuccessDesc: "{count} resi telah berhasil diperbarui menjadi \"Dikirim\".",
                bulkProcessError: "Gagal Memproses",
                bulkProcessErrorDesc: "Terjadi kesalahan saat memperbarui status resi.",
            },
            returnPage: {
                title: "Kelola Return & Resi Batal",
                table: {
                    awb: "No. Resi (AWB)",
                    date: "Tanggal",
                    channel: "Channel",
                    status: "Status",
                    actions: "Aksi",
                },
                actions: {
                    process: "Proses",
                    itemArrived: "Barang Sampai",
                    itemInTransit: "Diantar",
                    itemNotArrived: "Tidak Sampai",
                    delete: "Hapus",
                },
                loading: "Memuat data...",
                noReturnsTitle: "Belum ada data return",
                noReturnsDesc: "Semua resi return/batal akan muncul di sini.",
                fetchError: "Gagal memuat data return.",
                statusUpdateSuccess: "Status Diperbarui",
                statusUpdateSuccessDesc: "Status resi telah diubah menjadi \"{status}\".",
                statusUpdateError: "Gagal Memperbarui Status",
                processReturn: "Proses Return",
                selectReturnedItem: "Pilih produk yang dikembalikan untuk ditambahkan ke stok.",
                stockReturnedSuccess: "Stok Dikembalikan",
                stockReturnedSuccessDesc: "1 item {name} telah ditambahkan kembali ke stok.",
                stockReturnedError: "Gagal mengembalikan stok.",
                deleteConfirmTitle: "Hapus Data Return Ini?",
                deleteConfirmDesc: "Anda yakin ingin menghapus catatan return untuk {awb}? Tindakan ini tidak bisa dibatalkan.",
                deleteConfirmAction: "Ya, Hapus",
                deleteSuccess: "Data Return Dihapus",
                deleteSuccessDesc: "Catatan return untuk {awb} telah berhasil dihapus.",
                deleteError: "Gagal menghapus data return.",
            },
            reportPage: {
                title: "Laporan Resi",
                selectMonth: "Pilih Bulan",
                selectYear: "Pilih Tahun",
                table: {
                    date: "Tanggal",
                    pending: "Perlu Diproses",
                    shipped: "Dikirim",
                    cancelled: "Batal",
                    returned: "Return",
                    total: "Total Resi",
                },
                fetchError: "Gagal memuat data laporan.",
                noDataTitle: "Tidak Ada Data",
                noDataDesc: "Tidak ada data resi pada bulan yang dipilih.",
            }
        },
        finance: {
            title: "Keuangan",
            generalJournal: "Jurnal Umum",
            generalLedger: "Buku Besar",
            financialStatements: "Laporan Keuangan",
            assetReport: "Laporan Aset",
            profitLossReport: "Laporan Laba Rugi",
            priceSettings: "Pengaturan Harga",
            balanceSheet: "Neraca",
            priceSettingsPage: {
                description: "Pilih produk untuk mengatur harga modal, harga jual default, dan harga spesifik per kanal penjualan.",
                selectProduct: "Pilih Produk",
                searchPlaceholder: "Cari produk di dalam tabel...",
                product: "Produk",
                costPrice: "Harga Modal",
                defaultPrice: "Harga Default",
                onlinePrice: "Harga Online",
                sellingPrices: "Harga Jual",
                noProducts: "Belum ada produk dipilih.",
                selectProductsCta: "Pilih produk untuk mulai mengatur harga.",
                saveAll: "Simpan Semua Perubahan",
                successToast: "Harga Diperbarui",
                successToastDesc: "Semua perubahan harga telah berhasil disimpan.",
                errorToast: "Pembaruan Gagal",
                channelPriceDetails: "Rincian Harga Kanal",
            },
            assetReportPage: {
                totalAssetValue: "Total Nilai Aset",
                fastLabel: "Lancar",
                slowLabel: "Lambat",
                nonMovingLabel: "Tidak Lancar",
                chartTitle: "Grafik Perputaran Aset",
                chartXAxisLabel: "Klasifikasi Aset",
                topFastMoving: "10 Produk Terlaris",
                topSlowMoving: "10 Produk Lambat",
                topNonMoving: "10 Produk Tidak Lancar",
                productColumn: "Produk",
                unitsSoldColumn: "Terjual",
                stockValueColumn: "Nilai Stok",
                noProductsInCategory: "Tidak ada produk di kategori ini."
            }
        },
        inventoryTable: {
            searchPlaceholder: "Cari barang...",
            selectCategoryPlaceholder: "Pilih kategori",
            allCategories: "Semua Kategori",
            exportCsv: "Ekspor CSV",
            name: "Nama",
            size: "Ukuran",
            price: "Harga",
            currentStock: "Stok Saat Ini",
            actions: "Aksi",
            updateStock: "Perbarui Stok",
            viewHistory: "Lihat Riwayat",
            noItems: "Tidak ada barang ditemukan.",
            editProduct: "Ubah Produk",
            allStock: "Semua",
            lowStock: "Stok Menipis",
            emptyStock: "Stok Kosong",
        },
        archived: {
            title: "Produk Arsip",
            searchPlaceholder: "Cari produk di arsip...",
            archiveButton: "Arsipkan",
            unarchiveButton: "Aktifkan Kembali",
            deleteButton: "Hapus",
            table: {
                product: "Produk",
                category: "Kategori",
                actions: "Aksi",
            },
            loading: "Memuat produk arsip...",
            empty: "Tidak Ada Produk yang Diarsipkan",
            archiveSuccessTitle: "Produk Diarsipkan",
            archiveSuccessDesc: "Produk telah berhasil diarsipkan.",
            archiveErrorTitle: "Gagal Mengarsipkan",
            archiveErrorDesc: "Terjadi kesalahan saat mengarsipkan produk.",
            unarchiveSuccessTitle: "Produk Diaktifkan Kembali",
            unarchiveSuccessDesc: "Produk telah berhasil dikembalikan ke daftar aktif.",
            unarchiveErrorTitle: "Gagal Mengaktifkan Produk",
            unarchiveErrorDesc: "Terjadi kesalahan saat mengaktifkan kembali produk.",
            archiveDialogTitle: "Arsipkan Produk Ini?",
            archiveDialogDesc: "Produk yang diarsipkan akan disembunyikan dari daftar utama dan tidak bisa dijual. Anda bisa mengaktifkannya kembali nanti.",
            archiveDialogConfirm: "Ya, Arsipkan",
            deleteDialogTitle: "Hapus Produk Secara Permanen?",
            deleteDialogDesc: "Tindakan ini akan menghapus '{name}' dan semua datanya secara permanen. Tindakan ini tidak dapat diurungkan.",
            deleteDialogConfirm: "Ya, Hapus Permanen",
            deleteSuccessTitle: "Produk Dihapus",
            deleteSuccessDesc: "{name} telah berhasil dihapus secara permanen.",
            deleteErrorTitle: "Gagal Menghapus",
            deleteErrorDesc: "Terjadi kesalahan saat menghapus produk."
        },
        addItemDialog: {
            title: "Tambah Barang Baru",
            description: "Masukkan detail barang inventaris baru.",
            itemName: "Nama Barang",
            itemNamePlaceholder: "cth., Teh Hijau Organik",
            category: "Kategori",
            categoryPlaceholder: "Pilih Kategori",
            price: "Harga",
            pricePlaceholder: "cth., 50000",
            initialStock: "Stok Awal",
            initialStockPlaceholder: "cth., 100",
            addItem: "Tambah Barang",
            itemAdded: "Barang Ditambahkan",
            hasBeenAdded: "telah ditambahkan ke inventaris.",
        },
        updateStockDialog: {
            stockUpdated: "Stok Diperbarui",
            stockFor: "Stok untuk",
            hasBeenAdjusted: "telah disesuaikan.",
            title: "Perbarui Stok",
            description: "Stok saat ini:",
            stockAdjustment: "Perubahan Stok",
            stockAdjustmentPlaceholder: "cth., +10 untuk masuk, -5 untuk keluar",
            newStockLevel: "Jumlah Stok Baru",
            reason: "Alasan Penyesuaian",
            reasonPlaceholder: "cth., Penjualan, Kiriman Baru, Koreksi",
            updateStock: "Perbarui Stok",
            stockMustBePositive: "Stok harus berupa angka non-negatif.",
            reasonRequired: "Alasan harus diisi minimal 2 karakter.",
        },
        stockHistory: {
            title: "Riwayat Stok",
            description: "Log dari semua penyesuaian stok untuk barang ini.",
            date: "Tanggal",
            reason: "Alasan",
            change: "Perubahan",
            newTotal: "Total Baru",
            searchPlaceholder: "Cari berdasarkan nama produk atau alasan...",
            dateRange: "Rentang Tanggal",
        },
        stockInForm: {
            title: "Catat Stok Masuk",
            description: "Tambahkan stok baru yang diterima dari pemasok atau sumber lain.",
            selectProducts: "Pilih Produk",
            noProducts: "Belum ada produk dipilih.",
            quantity: "Jumlah",
            reason: "Alasan / Catatan",
            submit: "Kirim Stok Masuk",
            successTitle: "Stok Masuk Berhasil",
            successDescription: "{count} barang telah diperbarui.",
            bulkAdd: "Tambah Massal",
        },
        productSelectionDialog: {
            title: "Pilih Produk",
            description: "Pilih produk untuk ditambahkan ke daftar. Anda dapat mencari, memfilter, dan memilih beberapa item.",
            searchPlaceholder: "Cari berdasarkan produk atau SKU...",
            categoryPlaceholder: "Filter berdasarkan kategori...",
            addItems: "Tambah {count} Barang",
            itemsPerPage: "Menampilkan {start}-{end} dari {total} barang.",
            previous: "Sebelumnya",
            next: "Berikutnya",
            page: "halaman",
            of: "dari",
        },
        variantSelectionDialog: {
            title: "Pilih Varian",
            description: "Produk ini memiliki beberapa varian. Silakan pilih salah satu untuk melanjutkan penjualan."
        },
        pos: {
            title: "Point of Sale",
            searchPlaceholder: "Scan SKU atau cari nama produk...",
            noResults: "Produk tidak ditemukan.",
            noStock: "Stok habis",
            orderSummary: "Ringkasan Pesanan",
            item: "Barang",
            qty: "Jml",
            price: "Harga",
            subtotal: "Subtotal",
            emptyCart: "Keranjang kosong",
            paymentDetails: "Detail Pembayaran",
            discount: "Diskon (Rp)",
            tax: "Pajak (%)",
            cashReceived: "Uang Tunai",
            total: "Total",
            change: "Kembalian",
            completeSale: "Selesaikan Penjualan",
            saleCompleted: "Penjualan Selesai",
            transactionId: "ID Transaksi:",
            printReceipt: "Cetak Struk",
            newSale: "Penjualan Baru",
            history: "Riwayat Transaksi",
            cancel: "Batalkan Penjualan",
            transactionCancelled: "Transaksi Dibatalkan",
            paymentMethod: "Metode Bayar",
            cash: "Tunai",
        },
        reseller: {
            selectTitle: "Pilih Reseller",
            selectDescription: "Pilih reseller untuk memulai transaksi.",
            selectOrCreate: "Pilih atau Tambah Reseller",
            historyTitle: "Riwayat Transaksi Reseller",
            transactionsOnDate: "Transaksi pada {date}",
            transactionsDescription: "Menampilkan semua transaksi dari channel Reseller.",
            noTransactions: "Tidak Ada Transaksi",
            noTransactionsDesc: "Tidak ada transaksi yang tercatat pada tanggal yang dipilih.",
            history: {
                time: "Waktu",
                reseller: "Reseller",
                transactionDetails: "Detail Transaksi",
                paymentMethod: "Metode Bayar",
                total: "Total",
                actions: "Aksi"
            },
            dialog: {
                title: "Pilih Reseller",
                description: "Pilih reseller dari daftar di bawah, atau tambahkan yang baru.",
                addNew: "Tambah Reseller Baru",
                searchPlaceholder: "Cari reseller...",
                table: {
                    name: "Nama",
                    phone: "No. Telepon",
                    address: "Alamat",
                    actions: "Aksi",
                },
                form: {
                    addTitle: "Tambah Reseller Baru",
                    addDescription: "Masukkan detail reseller baru di bawah ini.",
                    editTitle: "Ubah Reseller",
                    editDescription: "Ubah detail reseller di bawah ini.",
                    nameLabel: "Nama Reseller",
                    namePlaceholder: "Nama...",
                    phoneLabel: "No. Telepon",
                    phonePlaceholder: "0812...",
                    addressLabel: "Alamat",
                    addressPlaceholder: "Alamat singkat...",
                    save: "Simpan Reseller"
                },
                deleteDialog: {
                    title: "Anda yakin ingin menghapus reseller ini?",
                    description: "Tindakan ini tidak dapat diurungkan. Ini akan menghapus reseller '{name}' secara permanen.",
                    confirm: "Ya, Hapus"
                },
                addedToast: "Reseller Ditambahkan",
                addedToastDesc: "Reseller '{name}' berhasil ditambahkan.",
                addErrorToast: "Gagal Menambahkan",
                updatedToast: "Reseller Diperbarui",
                updatedToastDesc: "Data untuk '{name}' telah diperbarui.",
                updateErrorToast: "Gagal Memperbarui",
                deletedToast: "Reseller Dihapus",
                deletedToastDesc: "Reseller '{name}' telah dihapus.",
                deleteErrorToast: "Gagal Menghapus",
                notFound: "Reseller tidak ditemukan.",
                none: "Belum ada reseller. Tambahkan di atas."
            }
        },
        receipt: {
            shopName: "WaveApp Store",
            thankYou: "Terima kasih telah berbelanja!",
            date: "Tanggal",
            receiptNo: "No. Struk",
            cashier: "Kasir",
            paymentMethod: "Metode Bayar",
            item: "Barang",
            qty: "Jml",
            price: "Harga",
            total: "Total",
            subtotal: "Subtotal",
            discount: "Diskon",
            grandTotal: "Grand Total",
            cash: "Tunai",
            change: "Kembalian",
        },
        settings: {
            back: "Kembali",
            title: "Pengaturan",
            appearance: "Tampilan",
            appearanceDescription: "Sesuaikan tampilan dan nuansa aplikasi.",
            theme: "Tema",
            selectThemePlaceholder: "Pilih tema",
            light: "Terang",
            dark: "Gelap",
            system: "Sistem",
            language: "Bahasa",
            languageDescription: "Pilih bahasa pilihan Anda.",
            selectLanguagePlaceholder: "Pilih bahasa",
        },
        bulkEditDialog: {
            title: "Atur Stok",
            parentSkuLabel: "SKU Induk",
            bulkStockPlaceholder: "Atur Stok Massal",
            applyToAll: "Terapkan semua",
            variationColumn: "Variasi",
            totalStockColumn: "Total Stok",
            reasonLabel: "Alasan Penyesuaian",
            reasonPlaceholder: "cth., Stok Opname, Koreksi...",
            defaultReason: "Penyesuaian Stok Massal",
            successToastTitle: "Varian Diperbarui",
            successToastDesc: "Stok untuk varian {name} telah diperbarui.",
            invalidValueToastTitle: "Nilai Tidak Valid",
            invalidValueToastDesc: "Harap masukkan jumlah stok yang valid (angka non-negatif)."
        },
        bulkStockInDialog: {
            title: "Stok Masuk Massal",
            description: "Atur jumlah dan alasan untuk semua barang terpilih dengan cepat. Ini akan menimpa nilai yang sudah ada.",
            variantName: "Nama Varian",
            applyToAll: "Terapkan ke Semua",
            applyReasonPlaceholder: "Atur alasan untuk semua varian...",
            hasVariants: "Produk ini memiliki banyak varian (misalnya ukuran, warna)",
            variants: "Varian",
            variantsDescription: "Tambahkan varian untuk produk Anda. Setiap varian dapat memiliki SKU, harga, dan tingkat stok sendiri.",
            addVariant: "Tambah Varian"
        },
        common: {
            cancel: "Batal",
            saveChanges: "Simpan Perubahan",
            apply: "Terapkan",
            saving: 'Menyimpan...',
            update: "Perbarui",
        }
    }
}
